const arabic = {
  main: {
    home: "الرئيسية",
    branches: "الفروع",
    choose_area: "اختر المنطقة",
    my_transactions: "المعاملات الاخيرة",
    my_vouchers: "القسائم المتاحة",
    my_gifts: "الهديا المتاحة",
    av_gifts_vouchers: "الهدايا والقسائم المتاحة",
    vouchers: " القسائم ",
    gifts: "الهدايا",
    panasonic_products: "منتجات باناسونيك",
    notifications: "الاشعارات",
    change_langauge: "تغيير اللغة",
    get_started: " البـدء",
    complaint: "شكوي",
    speak: "تحدث إلينا",
    inquery: "استعلام",
    previous_work: "سابقة أعمال",
    change: "تغيير",
    close: "اغلاق",
    send: "ارسال",
    no_notifications: "لا يوجد اشعارات جديدة",
    expiry_date: "تاريخ الانتهاء",
    redeem: "استبدال",
    show: "عـرض",
    verify: "التحقق باستخدام OTP",
    save: "حفظ",
    success_redeem: "تم الاستبدال بنجاح",
    posted_successfuly: "تم الارسال بنجاح",
    verify_text: "لقد ارسلنا رمز التحقق الي هذا الرقم",
    verify_enter: "ادخل الرمز هنا",
    verify_error: "الكود الذي تم ادخاله غير صحيح",
  },
  slider: {
    next: "التالي",
  },
  login: {
    title: "تسجيل الدخول",
    already_a_member: "عضوا فعلا",
    register_text: " ليس لديك حساب؟ سجل الآن ",
    mismatch_password: "كلمة المرور غير متطابقة",
    contain_space: "لا يجب ان تحتوي كلمة المرور علي مسافات",
    should_select_marital_status: "يجب اختيار الحالة الاجتماعية",
    user_must_be_older_than_18_years: "يجب ان يكون المستخدم اكبر من 18 عام",
    email_error: "تم استخدام هذا البريد الالكتروني مسبقاً",
    phone_error: "تم استخدام هذا الهاتف مسبقاً",
    forgot_password: "نسيت كلمة المرور ؟",
    resend_code: "اعادة ارسال الكود",
    no_phone_error: "رقم الهاتف لم يتم تسجيله من قبل",
    register_done_successfuly:
      "تم تسجيل المستخدم بنجاح سيتم تحويلك لشاشة تسجيل الدخول",
  },
  user: {
    email: "البريد الالكتروني",
    password: "كلمة المرور",
    confirm_password: "تأكيد كلمة المرور",
    city: "مدينة",
    name: "الاسم",
    material_status: "الحالة الإجتماعية",
    phone: "الهاتف",
    residency: "معرف الإقامة",
    birth_date: "تاريخ الميلاد ",
    register: "تسجيل",
    edit_profile: "تعديل البيانات",
    account_status: "حالة الحساب",
    accept:
      "من خلال الاشتراك أو تسجيل الدخول إلى هذا التطبيق ، فإنك توافق على الشروط والأحكام الخاصة بنا. الشروط وسياسة الخصوصية.",
  },
  account_statuses: {
    active: "نشط",
    stopped: "متوقف",
  },
  marital_statuses: {
    single: "اعزب",
    marreid: "متزوج",
  },
  watts: {
    title: "وات",
    available: " عدد الواتات المتاحة",
  },
  offers: {
    title: "العروض",
    redeem: "استبدال الواتس",
    production_date: "تاريخ العرض",
    model: "موديل ",
    you_will_get: "سوف تحصل علي",
  },
  menu: {
    profile: "الصفحة الشخصية ",
    contact: "اتصل بنا",
    tips: "اخبار ومعلومات",
    how: " كيف تعمل ",
    terms: " البنود والظروف ",
    privacy: " سياسة الخصوصية",
    help: "حول التطبيق",
    logout: " الخروج ",
    settings: "الإعدادات ",
  },
};

export default arabic;
