const arabic = {
  main: {
    home: "الرئيسية",
    branches: "الفروع",
    choose_area: "اختر المنطقة",
    my_transactions: "المعاملات الاخيرة",
    my_vouchers: "القسائم المتاحة",
    my_gifts: "الهديا المتاحة",
    av_gifts_vouchers: "الهدايا والقسائم المتاحة",
    vouchers: " القسائم ",
    gifts: "الهدايا",
    panasonic_products: "منتجات باناسونيك",
    notifications: "الاشعارات",
    change_langauge: "تغيير اللغة",
    get_started: " البـدء",
    complaint: "شكوي",
    speak: "تحدث إلينا",
    inquery: "استعلام",
    previous_work: "سابقة أعمال",
    change: "تغيير",
    close: "اغلاق",
    send: "ارسال",
    no_notifications: "لا يوجد اشعارات جديدة",
    expiry_date: "تاريخ الانتهاء",
    redeem: "استبدال",
    show: "عـرض",
    save: "حفظ",
  },
  slider: {
    next: "التالي",
  },
  login: {
    title: "تسجيل الدخول",
    already_a_member: "عضوا فعلا",
    register_text: " ليس لديك حساب؟ سجل الآن ",
  },
  user: {
    email: "البريد الالكتروني",
    password: "كلمة المرور",
    confirm_password: "تأكيد كلمة المرور",
    city: "مدينة",
    name: "الاسم",
    material_status: "الحالة الإجتماعية",
    phone: "الهاتف",
    residency: "معرف الإقامة",
    birth_date: "تاريخ الميلاد ",
    register: "تسجيل",
    edit_profile: "تعديل البيانات",
    accept:
      "من خلال الاشتراك أو تسجيل الدخول إلى هذا التطبيق ، فإنك توافق على الشروط والأحكام الخاصة بنا. الشروط وسياسة الخصوصية.",
  },
  marital_statuses: {
    single: "اعزب",
    marreid: "متزوج",
  },
  watts: {
    title: "وات",
    available: " عدد الواتات المتاحة",
  },
  offers: {
    title: "العروض",
    redeem: "استبدال الواتس",
    production_date: "تاريخ العرض",
    model: "موديل ",
    you_will_get: "سوف تحصل علي",
  },
  menu: {
    profile: "الصفحة الشخصية ",
    contact: "اتصل بنا",
    tips: "اخبار ومعلومات",
    how: " كيف تعمل ",
    terms: " البنود و الظروف ",
    privacy: " سياسة خاصة ",
    help: " جهاز / مساعدة",
    logout: " الخروج ",
    settings: "الإعدادات ",
  },
};

export default arabic;
