const bn = {
  main: {
    home: "বাড়ি",
    branches: "শাখা",
    choose_area: "অঞ্চল নির্বাচন করুন",
    my_transactions: "আমার লেনদেন",
    my_vouchers: "আমার কুপন",
    my_gifts: "আমার উপহারগুলো",
    av_gifts_vouchers: "উপলভ্য উপহার এবং ভাউচার",
    vouchers: " ভাউচার ",
    gifts: "উপহার",
    panasonic_products: " প্যানাসোনিক পণ্য",
    notifications: "বিজ্ঞপ্তিগুলি",
    change_langauge: "ল্যাঙ্গেজ পরিবর্তন করুন",
    get_started: "এবার শুরু করা যাক",
    complaint: "অভিযোগ",
    speak: "আমাদের সাথে কথা বলুন",
    inquery: "Inquery",
    previous_work: "আগের কাজ",
    change: "পরিবর্তন",
    close: "ঘনিষ্ঠ",
    send: "পাঠান",
    no_notifications: "কোনও নতুন বিজ্ঞপ্তি নেই",
    expiry_date: "সমাপ্তির তারিখ ",
    redeem: "খালাস করা",
    show: "প্রদর্শনী",
    save: "সংরক্ষণ",
    success_redeem: "Redeem Done Successfuly !",
    posted_successfuly: "Posted Successfuly !",
    verify: "Verify using OTP !",
    verify_text: "We have sent a verification number to this phone",
    verify_enter: "Enter number here",
    verify_error: "The code you've entered is not Correct !",
  },
  slider: {
    next: "পরবর্তী",
  },
  login: {
    title: "এখনি প্রবেশ কর",
    already_a_member: "ইতোমধ্যে একজন সদস্য",
    register_text: "কোন অ্যাকাউন্ট নেই? এখন নিবন্ধন করুন",
    mismatch_password: "Mismatch Password",
    forgot_password: "Forgot password ?",
    resend_code: "Resend Code ?",
    contain_space: "Password should not contain spaces",
    should_select_marital_status: "Should Select Marital Status",
    user_must_be_older_than_18_years: "User must be older than 18 years",
    no_phone_error: "This phone number is not registered !",
    email_error: "Email Was Reisgered ",
    phone_error: "Phone is already registered",
    register_done_successfuly:
      "Register Done Successfuly, You will be redirected to login page",
  },
  user: {
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    confirm_password: "পাসওয়ার্ড নিশ্চিত করুন",
    city: "শহর",
    name: "নাম",
    material_status: "বৈবাহিক অবস্থা",
    phone: "ফোন",
    residency: "আবাস",
    birth_date: "জন্ম তারিখ",
    register: "নিবন্ধন",
    edit_profile: "জীবন বৃত্তান্ত সম্পাদনা",
    account_status: "অ্যাকাউন্টের স্থিতি",
    accept:
      "এই অ্যাপ্লিকেশনটিতে সাইন আপ বা লগ ইন করে আপনি আমাদের শর্তাদি এবং শর্তাদি এবং গোপনীয়তা নীতিতে সম্মত হন।",
  },
  marital_statuses: {
    single: "একক",
    marreid: "Marreid",
  },
  account_statuses: {
    active: "সক্রিয়",
    stopped: "বন্ধ",
  },
  watts: {
    title: "ওয়াটস",
    available: "অ্যাভিলেবল ওয়াটস",
  },
  offers: {
    title: "অফার",
    redeem: "ওয়াটস মুক্ত করুন",
    production_date: "অফার তারিখ",
    model: "পণ্যের ধরণ",
    you_will_get: "তুমি পাবে",
  },
  menu: {
    profile: "আমার প্রোফাইল",
    contact: "যোগাযোগ করুন",
    how: " কিভাবে এটা কাজ করে",
    tips: "খবর এবং টিপস",
    terms: " শর্তাবলী",
    privacy: " গোপনীয়তা নীতি",
    help: " ডিভাইস / ইঙ্গিতগুলি",
    logout: " প্রস্থান",
    settings: "সেটিংস",
  },
};

export default bn;
