const english = {
  main: {
    home: "Home",
    branches: "Branches",
    choose_area: "Choose Area",
    my_transactions: "My Transactions",
    my_vouchers: "My Vouchers",
    my_gifts: "My Gifts",
    av_gifts_vouchers: "Avilable Gifts & Vouchers",
    vouchers: " Vouchers ",
    gifts: "Gifts",
    panasonic_products: " Panasonic Products",
    notifications: "Notifications",
    change_langauge: "Change Langauge",
    get_started: "Get Started",
    complaint: "Complaint",
    speak: "Speak to us",
    inquery: "Inquery",
    previous_work: "Previous Work",
    change: "Change",
    close: "Close",
    send: "Send",
    no_notifications: "There are no new notifications",
    expiry_date: "Expiry Date ",
    redeem: "Redeem",
  },
  slider: {
    next: "Next",
  },
  login: {
    title: "Login Now",
    already_a_member: "Already a member",
    register_text: "Don't have an account ? Register Now",
  },
  user: {
    email: "Email",
    password: "Password",
    city: "City",
    name: "Name",
    material_status: "Material Status",
    phone: "Phone",
    residency: "Residency",
  },
  watts: {
    title: "Watts",
    available: "Avilable Watts",
  },
  offers: {
    title: "Offers",
    redeem: "Redeem Watts",
    production_date: "Offer Date",
    model: "Product Model",
    you_will_get: "You will get",
  },
  menu: {
    profile: "My Profile",
    contact: "Contact Us",
    how: " How it works",
    tips: "News and tips",
    terms: " Terms & conditions",
    privacy: " Privacy policy",
    help: " Device / Hints",
    logout: " Logout",
    settings: "Settings",
  },
};

export default english;
