const hi = {
  main: {
    home: "घर",
    branches: "शाखाओं",
    choose_area: "क्षेत्र चुनें",
    my_transactions: "मेरे लेन-देन",
    my_vouchers: "मेरे वाउचर",
    my_gifts: "मेरे तोहफे",
    av_gifts_vouchers: "Avilable उपहार और वाउचर",
    vouchers: " वाउचर ",
    gifts: "उपहार",
    panasonic_products: " पैनासोनिक उत्पाद",
    notifications: "सूचनाएं",
    change_langauge: "लैंग्वेज को बदलें",
    get_started: "शुरू हो जाओ",
    complaint: "शिकायत",
    speak: "हमसे बोलो",
    inquery: "inquery",
    previous_work: "पिछला कार्य",
    change: "परिवर्तन",
    close: "बंद करे",
    send: "संदेश",
    no_notifications: "कोई नई सूचना नहीं है",
    expiry_date: "समाप्ति तिथि ",
    redeem: "के एवज",
    show: "प्रदर्शन",
    save: "सहेजें",
    success_redeem: "Redeem Done Successfuly !",
  },
  slider: {
    next: "आगे",
  },
  login: {
    title: "अब प्रवेश करें",
    already_a_member: "पहले से सदस्य हैं",
    register_text: "खाता नहीं है? अभी पंजीकरण करें",
    mismatch_password: "Mismatch Password",
    contain_space: "Password should not contain spaces",
    should_select_marital_status: "Should Select Marital Status",
    user_must_be_older_than_18_years: "User must be older than 18 years",
    email_error: "Email Was Reisgered ",
    register_done_successfuly:
      "Register Done Successfuly, You will be redirected to login page",
  },
  user: {
    email: "ईमेल",
    password: "कुंजिका",
    confirm_password: "पासवर्ड की पुष्टि कीजिये",
    city: "Faridabad",
    name: "नाम",
    material_status: "सामग्री की स्थिति",
    phone: "फ़ोन",
    residency: "निवास",
    birth_date: "जन्म दिन",
    register: "रजिस्टर करें",
    edit_profile: "प्रोफ़ाइल संपादित करें",
    account_status: "खाते की स्थिति",
    accept:
      "इस ऐप में साइन अप या लॉग इन करके, आप हमारे नियम और शर्तों और गोपनीयता नीति से सहमत होते हैं।",
  },
  marital_statuses: {
    single: "एक",
    marreid: "Marreid",
  },
  account_statuses: {
    active: "सक्रिय",
    stopped: "रोका हुआ",
  },
  watts: {
    title: "वत्स",
    available: "एविलेबल वॉट्स",
  },
  offers: {
    title: "ऑफर",
    redeem: "वत्स छुड़ाना",
    production_date: "प्रस्ताव तिथि",
    model: "उत्पाद नमूना",
    you_will_get: "तुम्हे मिल जाएगा",
  },
  menu: {
    profile: "मेरी प्रोफाइल",
    contact: "संपर्क करें",
    how: " यह काम किस प्रकार करता है",
    tips: "समाचार और टिप्स",
    terms: " नियम एवं शर्तें",
    privacy: " गोपनीयता नीति",
    help: " डिवाइस / संकेत",
    logout: " लॉग आउट",
    settings: "समायोजन",
  },
};

export default hi;
